# Generated by Django 4.1.3 on 2022-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mensaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=60)),
                ('Imagen', models.ImageField(upload_to='')),
                ('Precio', models.FloatField()),
            ],
        ),
    ]
