# Generated by Django 4.1.3 on 2022-12-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='Descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='Imagen',
            field=models.ImageField(upload_to='galeria'),
        ),
    ]
